project:
  type: website
  output-dir: ../docs
website:
  title: University Course Portal
  navbar:
    left:
    - href: /index.html
      text: Home
    - text: Courses
      menu:
      - text: First Semester
        href: /index.html#1sem
      - text:  LCPA · Theory
        href: /1sem/LCPA/index.html
      - text:  LCPA · Projects
        href: /1sem/LCPA/projects.html
      - text:  MAPDA · Theory
        href: /1sem/MAPDA/index.html
      - text:  ML · Theory
        href: /1sem/ML/index.html
      - text:  MTP · Theory
        href: /1sem/MTP/index.html
      - text:  QIAP · Projects
        href: /1sem/QIAP/projects.html
      - text: '---'
      - text: Second Semester
        href: /index.html#2sem
      - text:  ASPA · Theory
        href: /2sem/ASPA/index.html
      - text:  ASPA · Projects
        href: /2sem/ASPA/projects.html
      - text:  LCPB · Theory
        href: /2sem/LCPB/index.html
      - text:  LCPB · Projects
        href: /2sem/LCPB/projects.html
      - text:  MAPDB · Theory
        href: /2sem/MAPDB/index.html
      - text:  MAPDB · Projects
        href: /2sem/MAPDB/projects.html
      - text:  PCN · Theory
        href: /2sem/PCN/index.html
      - text:  PCN · Projects
        href: /2sem/PCN/projects.html
      - text: '---'
      - text: Third Semester
        href: /index.html#3sem
      - text:  (none yet)
        href: '#'
      - text: '---'
      - text: Fourth Semester
        href: /index.html#4sem
      - text:  (none yet)
        href: '#'
    right:
    - icon: github
      href: https://github.com/
  search: true
format:
  html:
    theme:
    - cosmo
    - ../unipd-style.css
    toc: true
    toc-depth: 2
    embed-resources: false
    self-contained: false
    page-layout: full
