project:
  type: website
  output-dir: ../docs
website:
  title: University Course Portal
  navbar:
    left:
    - href: index.qmd
      text: Home
    - text: Courses
      menu:
      - text: First Semester
        menu:
        - text: LCPA
          href: /1sem/LCPA/index.html
        - text: MAPDA
          href: /1sem/MAPDA/index.html
        - text: ML
          href: /1sem/ML/index.html
        - text: MTP
          href: /1sem/MTP/index.html
        - text: QIAP
          href: /1sem/QIAP/index.html
      - text: Second Semester
        menu:
        - text: ASPA
          href: /2sem/ASPA/index.html
        - text: IQH
          href: /2sem/IQH/index.html
        - text: LCPB
          href: /2sem/LCPB/index.html
        - text: MAPDB
          href: /2sem/MAPDB/index.html
        - text: PCN
          href: /2sem/PCN/index.html
      - text: Third Semester
      - text: Fourth Semester
    right:
    - icon: github
      href: https://github.com/
format:
  html:
    theme: cosmo
    toc: true
