<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Risk-free rates in practice – Stochastic Finance</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/10-fx-options-market-making.html" rel="next">
<link href="../chapters/08-interest-rate-modeling.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-12757e4b7af482b2d9c5bd8860d2b707.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3fda7689cb8c4ed59160d7ff94eb8d4f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/09-risk-free-rates-in-practice.html">Part III: Practitioner lectures</a></li><li class="breadcrumb-item"><a href="../chapters/09-risk-free-rates-in-practice.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Risk-free rates in practice</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Stochastic Finance</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About these notes</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I: Markets and no-arbitrage</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-financial-markets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">An introduction to financial markets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-financial-derivatives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Financial derivatives</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-binomial-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The binomial model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: Continuous-time models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-brownian-motion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Brownian motion and stochastic calculus</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-black-scholes-merton.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Black–Scholes–Merton model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-monte-carlo-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Monte Carlo methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-volatility-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Volatility modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-interest-rate-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interest rate modelling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: Practitioner lectures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-risk-free-rates-in-practice.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Risk-free rates in practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-fx-options-market-making.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">FX options and automated market making</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-fixed-income-market" id="toc-the-fixed-income-market" class="nav-link active" data-scroll-target="#the-fixed-income-market"><span class="header-section-number">9.1</span> The fixed-income market</a></li>
  <li><a href="#market-conventions" id="toc-market-conventions" class="nav-link" data-scroll-target="#market-conventions"><span class="header-section-number">9.2</span> Market conventions</a></li>
  <li><a href="#from-ibors-to-rfrs" id="toc-from-ibors-to-rfrs" class="nav-link" data-scroll-target="#from-ibors-to-rfrs"><span class="header-section-number">9.3</span> From IBORs to RFRs</a></li>
  <li><a href="#backward-looking-rates" id="toc-backward-looking-rates" class="nav-link" data-scroll-target="#backward-looking-rates"><span class="header-section-number">9.4</span> Backward-looking rates</a>
  <ul class="collapse">
  <li><a href="#overnight-indexed-swaps" id="toc-overnight-indexed-swaps" class="nav-link" data-scroll-target="#overnight-indexed-swaps"><span class="header-section-number">9.4.1</span> Overnight indexed swaps</a></li>
  <li><a href="#swaptions" id="toc-swaptions" class="nav-link" data-scroll-target="#swaptions"><span class="header-section-number">9.4.2</span> Swaptions</a></li>
  <li><a href="#caplets-on-backward-looking-rates" id="toc-caplets-on-backward-looking-rates" class="nav-link" data-scroll-target="#caplets-on-backward-looking-rates"><span class="header-section-number">9.4.3</span> Caplets on backward-looking rates</a></li>
  </ul></li>
  <li><a href="#bootstrapping-an-rfr-curve" id="toc-bootstrapping-an-rfr-curve" class="nav-link" data-scroll-target="#bootstrapping-an-rfr-curve"><span class="header-section-number">9.5</span> Bootstrapping an RFR curve</a></li>
  <li><a href="#risk-free-rates-in-insurance-solvency-ii" id="toc-risk-free-rates-in-insurance-solvency-ii" class="nav-link" data-scroll-target="#risk-free-rates-in-insurance-solvency-ii"><span class="header-section-number">9.6</span> Risk-free rates in insurance: Solvency II</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">9.7</span> Exercises</a></li>
  <li><a href="#sources" id="toc-sources" class="nav-link" data-scroll-target="#sources"><span class="header-section-number">9.8</span> Sources</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/09-risk-free-rates-in-practice.html">Part III: Practitioner lectures</a></li><li class="breadcrumb-item"><a href="../chapters/09-risk-free-rates-in-practice.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Risk-free rates in practice</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Risk-free rates in practice</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<p>Chapter 8 treated the risk-free curve as a given mathematical object. In practice it has to be <strong>built</strong> from market quotes, under precise conventions, and since 2023 from a new family of benchmarks. This chapter, based on a practitioner lecture by Vincenzo Russo (Assicurazioni Generali), covers market conventions, the transition from interbank offered rates (IBORs) to overnight risk-free rates (RFRs), the pricing of overnight indexed swaps, swaptions and caplets on <strong>backward-looking</strong> rates, the bootstrap of an RFR curve, and the use of risk-free curves in the insurance sector under Solvency II.</p>
<section id="the-fixed-income-market" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="the-fixed-income-market"><span class="header-section-number">9.1</span> The fixed-income market</h2>
<p>The fixed-income market trades debt securities that pay predetermined cash flows: government bonds, corporate and covered bonds, municipal bonds, securitised products (MBS, ABS), money-market instruments. Issuers are sovereigns and financial or non-financial corporates; investors (asset managers, insurers, banks, pension funds) seek income, capital preservation, diversification and <strong>liability matching</strong>. Bonds differ by maturity (money market below 1 year, short 1–3, intermediate 3–7, long beyond 7), currency, structure (fixed, floating, inflation-linked, callable or putable, securitised) and credit rating (AAA down to D).</p>
<p>Prices and yields move inversely. The total yield of a risky bond decomposes as <span class="math display">\[\text{yield} = \text{risk-free rate} + \text{credit spread} + \text{liquidity premium},\]</span> so the risk-free curve is the reference for everything: <strong>discounting</strong> cash flows (time value of money without credit risk), <strong>forwarding</strong> floating rates (forward rates implied by no arbitrage), risk measures (duration, DV01, convexity), the risk-neutral drift in option pricing, and, for insurers, the fair value of both assets and liabilities.</p>
<p><strong>Risk-free proxies.</strong> No asset is truly risk-free. Proxies are short-term rates anchored by central banks — government bills of top-rated sovereigns, and the new overnight benchmarks €STR (euro), SOFR (US), SONIA (UK), SARON (Switzerland), TONA (Japan) — and the derivatives written on them: futures, overnight indexed swaps (OIS). Risk-free rates are nominal: real rate plus expected inflation.</p>
</section>
<section id="market-conventions" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="market-conventions"><span class="header-section-number">9.2</span> Market conventions</h2>
<p><strong>Day counts.</strong> The <strong>year fraction</strong> <span class="math inline">\(\tau(t, T)\)</span> between two dates depends on the day-count convention: ACT/360 (actual days divided by 360, standard for money markets), ACT/365, ACT/ACT, 30/360. For ACT/360, <span class="math inline">\(\tau(T_{i-1}, T_i) = (T_i - T_{i-1})/360\)</span> with dates counted in days.</p>
<p><strong>Business-day rules</strong> adjust payment dates falling on holidays: <em>Following</em> (next business day), <em>Modified Following</em> (next business day unless it crosses into the next month, then the previous one), <em>Unadjusted</em>.</p>
<p><strong>Compounding.</strong> A ZCB price <span class="math inline">\(P(t, T)\)</span> defines a spot rate in each convention:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">compounding</th>
<th style="text-align: left;">definition</th>
<th style="text-align: left;">rate from price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">simple</td>
<td style="text-align: left;"><span class="math inline">\(P = \dfrac{1}{1 + \tau R_s}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(R_s = \dfrac{1}{\tau}\Bigl(\dfrac1P - 1\Bigr)\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">annual</td>
<td style="text-align: left;"><span class="math inline">\(P = (1 + R_a)^{-\tau}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(R_a = P^{-1/\tau} - 1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(k\)</span> times a year</td>
<td style="text-align: left;"><span class="math inline">\(P = \Bigl(1 + \dfrac{R_k}{k}\Bigr)^{-k\tau}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(R_k = k\bigl(P^{-1/(k\tau)} - 1\bigr)\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">continuous</td>
<td style="text-align: left;"><span class="math inline">\(P = e^{-R_c\tau}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(R_c = -\dfrac{\log P}{\tau}\)</span></td>
</tr>
</tbody>
</table>
<p>with <span class="math inline">\(\tau = \tau(t, T)\)</span>. The <strong>zero curve</strong> <span class="math inline">\(T \mapsto R_g(t, T)\)</span> depends on the convention <span class="math inline">\(g\)</span>; the <strong>discount curve</strong> <span class="math inline">\(T \mapsto P(t, T)\)</span> does not, and is decreasing from <span class="math inline">\(P(t, t) = 1\)</span> when rates are positive.</p>
<p><strong>Interpolation.</strong> Quotes exist only for some maturities, and are sparse or illiquid at the long end. Missing points are interpolated — linearly, by cubic splines, or with parametric families such as Nelson–Siegel. For par rates <span class="math inline">\(S_{T_{i-1}}, S_{T_i}\)</span> quoted at consecutive maturities, linear interpolation gives, for <span class="math inline">\(T_{i-1} &lt; T_h &lt; T_i\)</span>, <span class="math display">\[S_{T_h} = \frac{S_{T_{i-1}}(T_i - T_h) + S_{T_i}(T_h - T_{i-1})}{T_i - T_{i-1}} .\]</span></p>
<p><strong>Bonds.</strong> A fixed-rate bond with coupon rate <span class="math inline">\(K\)</span> and dates <span class="math inline">\(T_1, \dots, T_n\)</span> is worth <span class="math display">\[B_{fx}(t, T_n) = \sum_{i=1}^nP(t, T_i)\,\tau(T_{i-1}, T_i)\,K + P(t, T_n).\]</span> For a <strong>defaultable</strong> issuer, market practice discounts with the risk-free zero rate plus a <strong>zero spread</strong> <span class="math inline">\(S\)</span>: with annual compounding <span class="math inline">\(\bar P(t, T) = (1 + R_a(t, T) + S)^{-\tau(t,T)}\)</span>, and the bond price uses <span class="math inline">\(\bar P\)</span> in place of <span class="math inline">\(P\)</span>.</p>
</section>
<section id="from-ibors-to-rfrs" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="from-ibors-to-rfrs"><span class="header-section-number">9.3</span> From IBORs to RFRs</h2>
<p>IBORs (Libor, Euribor) were for decades the benchmark for loans, notes and derivatives, and together with overnight rates (Fed Funds, EONIA) were treated as risk-free. During the 2007–2009 crisis the IBOR–overnight spread widened dramatically (Chapter 1), showing that IBORs contain bank credit and liquidity risk; IBOR quotes were also manipulated. Hence:</p>
<ul>
<li>2013–2014: the Financial Stability Board reviews the major benchmarks and recommends alternatives;</li>
<li>2017: the UK FCA announces it will stop supporting Libor panels;</li>
<li>2019: ISDA establishes fallbacks to transaction-based overnight RFRs;</li>
<li>Libor is discontinued (USD Libor on 30 June 2023), replaced by SOFR, SONIA, SARON, TONA; in the euro area €STR replaced EONIA, while <strong>Euribor survives</strong> in reformed, transaction-based form.</li>
</ul>
<p>The two kinds of rates differ structurally:</p>
<ul>
<li><strong>IBORs are forward-looking term rates</strong>: quoted for tenors from one week to one year as simple rates, fixed at the <em>start</em> of the accrual period — a market expectation.</li>
<li><strong>RFRs are backward-looking overnight rates</strong>: published daily, with no term structure of their own; the rate for a period is obtained by <strong>compounding the daily fixings in arrears</strong>, so it is known only at the <em>end</em> of the period.</li>
</ul>
<p>Correspondingly, three pricing environments have succeeded one another in a single currency:</p>
<ol type="1">
<li><strong>Single curve, IBOR</strong> (before 2007): IBOR rates for both discounting and forwarding.</li>
<li><strong>Dual curve</strong> (after 2007): overnight rates (EONIA, Fed Funds, now €STR, SOFR) for discounting, IBOR for forwarding — still the standard for Euribor derivatives.</li>
<li><strong>Single curve, RFR, backward-looking</strong>: the RFR curve for both discounting and forwarding. This is the setting of the rest of the chapter.</li>
</ol>
</section>
<section id="backward-looking-rates" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="backward-looking-rates"><span class="header-section-number">9.4</span> Backward-looking rates</h2>
<p>Let <span class="math inline">\(C(t) = \exp\bigl(\int_0^tr(u)\,du\bigr)\)</span> be the cash account driven by the instantaneous risk-free rate (Chapter 8), so that <span class="math inline">\(P(t, T) = \mathbb E^Q\bigl[e^{-\int_t^Tr(u)\,du}\bigm|\mathcal F_t\bigr]\)</span>.</p>
<div class="definition" name="Compounded-in-arrears RFR">
<p>For an accrual period <span class="math inline">\([T_{i-1}, T_i)\)</span> with <span class="math inline">\(d_i\)</span> business days, daily fixings <span class="math inline">\(r(i, j)\)</span> and day-count fractions <span class="math inline">\(\delta(i, j)\)</span>, <span class="math display">\[R(T_{i-1}, T_i) = \frac{1}{\tau(T_{i-1}, T_i)}\Bigl[\prod_{j=1}^{d_i}\bigl(1 + r(i, j)\delta(i, j)\bigr) - 1\Bigr] \;\approx\; \frac{1}{\tau(T_{i-1}, T_i)}\Bigl[\frac{C(T_i)}{C(T_{i-1})} - 1\Bigr],\]</span> the continuous-time version being the limit of vanishing daily steps.</p>
</div>
<div class="proposition" name="Forward value of a backward-looking rate">
<p>For <span class="math inline">\(t \leq T_{i-1}\)</span>, the expectation of <span class="math inline">\(R(T_{i-1}, T_i)\)</span> under the <span class="math inline">\(T_i\)</span>-forward measure (whose numeraire is <span class="math inline">\(P(\cdot, T_i)\)</span>) is <span class="math display">\[R(t, T_{i-1}, T_i) = \frac{1}{\tau(T_{i-1}, T_i)}\Bigl(\frac{P(t, T_{i-1})}{P(t, T_i)} - 1\Bigr),\]</span> the same formula as the simple forward rate of the IBOR world. For <span class="math inline">\(T_{i-1} &lt; t &lt; T_i\)</span> part of the rate is already known: <span class="math display">\[R(t, T_{i-1}, T_i) = \frac{1}{\tau(T_{i-1}, T_i)}\Bigl(\frac{e^{\int_{T_{i-1}}^tr(u)\,du}}{P(t, T_i)} - 1\Bigr).\]</span></p>
</div>
<p><em>Proof.</em> Under the <span class="math inline">\(T_i\)</span>-forward measure, <span class="math inline">\(\mathbb E^{T_i}[X\mid\mathcal F_t] = \mathbb E^Q\bigl[e^{-\int_t^{T_i}r}X\bigm|\mathcal F_t\bigr]/P(t, T_i)\)</span>. With <span class="math inline">\(X = C(T_i)/C(T_{i-1})\)</span>, <span class="math inline">\(e^{-\int_t^{T_i}r}X = e^{-\int_t^{T_{i-1}}r}\)</span>, whose <span class="math inline">\(Q\)</span>-expectation is <span class="math inline">\(P(t, T_{i-1})\)</span>. <span class="math inline">\(\square\)</span></p>
<section id="overnight-indexed-swaps" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="overnight-indexed-swaps"><span class="header-section-number">9.4.1</span> Overnight indexed swaps</h3>
<p>An <strong>OIS</strong> exchanges a fixed rate <span class="math inline">\(K\)</span> against the compounded RFR. A payer OIS with floating dates <span class="math inline">\(T_1, \dots, T_n\)</span>, fixed dates <span class="math inline">\(T'_1, \dots, T'_m\)</span> (same start and end), notional <span class="math inline">\(N\)</span>, valued at <span class="math inline">\(t &lt; T_0\)</span>: <span class="math display">\[OIS_R(t, T_0, T_n) = N\sum_{i=1}^nP(t, T_i)\tau(T_{i-1}, T_i)R(t, T_{i-1}, T_i) - N\sum_{j=1}^mP(t, T'_j)\tau(T'_{j-1}, T'_j)K .\]</span> By the proposition, before the start this coincides with the single-curve Libor swap formula (and the floating leg telescopes to <span class="math inline">\(N(P(t, T_0) - P(t, T_n))\)</span>). Once an accrual period has started, the known part of the compounded rate must be included: the first floating coupon becomes <span class="math inline">\(N\bigl(e^{\int_{T_0}^tr(u)\,du} - P(t, T_1)\bigr)\)</span>.</p>
</section>
<section id="swaptions" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="swaptions"><span class="header-section-number">9.4.2</span> Swaptions</h3>
<p>Assume the forward swap rate <span class="math inline">\(S_R(t, T_0, T_n)\)</span> is a log-normal martingale under the <strong>swap (annuity) measure</strong>, with numeraire the annuity <span class="math inline">\(A(t) = \sum_jP(t, T'_j)\tau(T'_{j-1}, T'_j)\)</span>: <span class="math display">\[\frac{dS_R(t, T_0, T_n)}{S_R(t, T_0, T_n)} = \sigma_S\,dW_t .\]</span> Then the payer swaption follows <strong>Black’s (1976) formula</strong> <span class="math display">\[PSWT_R(t) = N\,A(t)\bigl[S_R\Phi(d_1) - K\Phi(d_2)\bigr], \qquad d_{1,2} = \frac{\log(S_R/K) \pm \tfrac12\sigma_S^2(T_0 - t)}{\sigma_S\sqrt{T_0 - t}} .\]</span> Swaption valuation is <strong>unaffected</strong> by whether the underlying floating rate is forward- or backward-looking: what matters is the swap rate at <span class="math inline">\(T_0\)</span>.</p>
</section>
<section id="caplets-on-backward-looking-rates" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="caplets-on-backward-looking-rates"><span class="header-section-number">9.4.3</span> Caplets on backward-looking rates</h3>
<p>A caplet on <span class="math inline">\([T_{i-1}, T_i]\)</span> with strike <span class="math inline">\(K\)</span> pays <span class="math inline">\(N\tau(T_{i-1}, T_i)\bigl(R(T_{i-1}, T_i) - K\bigr)^+\)</span> at <span class="math inline">\(T_i\)</span>. The underlying rate keeps accruing during the period, so its uncertainty is resolved only at <span class="math inline">\(T_i\)</span>. Lyashenko and Mercurio (2019) model the forward rate as a log-normal martingale under the (extended) <span class="math inline">\(T_i\)</span>-forward measure, with a volatility that decays linearly during the accrual period: <span class="math display">\[\frac{dR(t, T_{i-1}, T_i)}{R(t, T_{i-1}, T_i)} = \sigma_R\min\Bigl(\frac{(T_i - t)^+}{T_i - T_{i-1}}, 1\Bigr)dW_t .\]</span> (The <em>extended</em> ZCB price — the bond maturing at <span class="math inline">\(T_i\)</span>, with proceeds rolled over at the RFR after <span class="math inline">\(T_i\)</span> — keeps the numeraire defined for <span class="math inline">\(t &gt; T_i\)</span>.) This gives a Black formula <span class="math display">\[CPLT_R(t) = N\tau(T_{i-1}, T_i)P(t, T_i)\bigl[R(t, T_{i-1}, T_i)\Phi(d_1) - K\Phi(d_2)\bigr], \qquad d_{1,2} = \frac{\log(R/K) \pm \tfrac12\Sigma_R^2}{\Sigma_R},\]</span> with total variance <span class="math display">\[\Sigma_R^2 = \sigma_R^2\int_t^{T_i}\min\Bigl(\frac{(T_i - s)^+}{T_i - T_{i-1}}, 1\Bigr)^2ds = \sigma_R^2\Bigl[\max(T_{i-1} - t, 0) + \frac{(T_i - \max(T_{i-1}, t))^3}{3(T_i - T_{i-1})^2}\Bigr].\]</span> Since a forward-looking caplet’s rate is fixed at <span class="math inline">\(T_{i-1}\)</span> (variance <span class="math inline">\(\sigma^2(T_{i-1} - t)\)</span>), <strong><span class="math inline">\(\Sigma_R \geq \Sigma_L\)</span></strong>: the backward-looking caplet carries the extra variance of the accrual period, a third of its length.</p>
<div class="example" name="Forward- vs backward-looking caplet">
<p>On the curve bootstrapped below, the at-the-money caplet on <span class="math inline">\([1, 2]\)</span> (forward rate <span class="math inline">\(3.407\%\)</span>) with <span class="math inline">\(\sigma = 20\%\)</span> is worth <span class="math inline">\(25.5\)</span> bp of notional if the rate is forward-looking (<span class="math inline">\(\Sigma_L = 0.2\sqrt1\)</span>) and <span class="math inline">\(29.4\)</span> bp if backward-looking (<span class="math inline">\(\Sigma_R = 0.2\sqrt{1 + 1/3} = 0.231\)</span>).</p>
</div>
<p>The same structure holds in the one- and two-factor Hull–White models, where the caplet becomes an option on <span class="math inline">\(C(T_i)/C(T_{i-1})\)</span> and <span class="math inline">\(\Sigma_R^2\)</span> splits into the variance of the bond’s forward price up to <span class="math inline">\(T_{i-1}\)</span> plus the extra variance accumulated over <span class="math inline">\([T_{i-1}, T_i]\)</span>.</p>
</section>
</section>
<section id="bootstrapping-an-rfr-curve" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="bootstrapping-an-rfr-curve"><span class="header-section-number">9.5</span> Bootstrapping an RFR curve</h2>
<p>RFR curves are stripped from OIS quoted <strong>at par</strong> (zero initial value), typically with annual payments on both legs. With spot start <span class="math inline">\(T_0 = 0\)</span> and par rates <span class="math inline">\(S_i = S_R(0, 0, T_i)\)</span>, setting the OIS value to zero for each maturity in turn, <span class="math display">\[P(0, T_1) = \frac{1}{1 + \tau_1S_1}, \qquad P(0, T_i) = \frac{1 - S_i\sum_{j=1}^{i-1}\tau_jP(0, T_j)}{1 + \tau_iS_i}, \quad i = 2, \dots, n,\]</span> with <span class="math inline">\(\tau_j = \tau(T_{j-1}, T_j)\)</span>. (This follows from the par condition <span class="math inline">\(1 - P(0, T_i) = S_i\sum_{j\leq i}\tau_jP(0, T_j)\)</span>, the telescoped floating leg equal to the fixed leg.)</p>
<div class="example" name="A five-year OIS bootstrap">
<p>Par rates (annual payments, <span class="math inline">\(\tau = 1\)</span>): 1y <span class="math inline">\(3.00\%\)</span>, 2y <span class="math inline">\(3.20\%\)</span>, 3y <span class="math inline">\(3.35\%\)</span>, 5y <span class="math inline">\(3.50\%\)</span>; the 4y rate is linearly interpolated, <span class="math inline">\(3.425\%\)</span>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(T\)</span></th>
<th style="text-align: center;">par rate</th>
<th style="text-align: center;"><span class="math inline">\(P(0, T)\)</span></th>
<th style="text-align: center;">zero rate (annual)</th>
<th style="text-align: center;">zero rate (cont.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">3.000%</td>
<td style="text-align: center;">0.97087</td>
<td style="text-align: center;">3.000%</td>
<td style="text-align: center;">2.956%</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">3.200%</td>
<td style="text-align: center;">0.93889</td>
<td style="text-align: center;">3.203%</td>
<td style="text-align: center;">3.153%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">3.350%</td>
<td style="text-align: center;">0.90568</td>
<td style="text-align: center;">3.357%</td>
<td style="text-align: center;">3.302%</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">3.425%</td>
<td style="text-align: center;">0.87365</td>
<td style="text-align: center;">3.435%</td>
<td style="text-align: center;">3.377%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">3.500%</td>
<td style="text-align: center;">0.84143</td>
<td style="text-align: center;">3.513%</td>
<td style="text-align: center;">3.453%</td>
</tr>
</tbody>
</table>
<p>With an upward-sloping curve, zero rates lie slightly above par rates, and forward rates above both (the 1-year forward from 4 to 5 years is <span class="math inline">\(3.83\%\)</span>).</p>
</div>
<p>In practice (e.g.&nbsp;SOFR on 30 September 2024) the procedure is the same with more instruments, real day counts, a few days’ spot lag and an interpolation scheme between pillars.</p>
</section>
<section id="risk-free-rates-in-insurance-solvency-ii" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="risk-free-rates-in-insurance-solvency-ii"><span class="header-section-number">9.6</span> Risk-free rates in insurance: Solvency II</h2>
<p>Under <strong>Solvency II</strong>, EU insurers compute their solvency ratio from a market-value balance sheet, valuing liabilities (technical provisions) and the Solvency Capital Requirement with a <strong>regulatory risk-free curve</strong> published by EIOPA:</p>
<ol type="1">
<li>collect par rates of IRS (Euribor) or OIS (SARON, SONIA, SOFR, …) for the liquid maturities (up to about 20 years for the euro);</li>
<li>subtract a <strong>credit risk adjustment</strong> (10 bp for Euribor-based curves, zero for RFR-based ones);</li>
<li><strong>bootstrap</strong> zero rates from the adjusted par rates;</li>
<li><strong>extrapolate</strong> beyond the last liquid point up to 150 years with the <strong>Smith–Wilson</strong> method, converging to an ultimate forward rate;</li>
<li>optionally add a <strong>volatility adjustment</strong> or <strong>matching adjustment</strong>, which reflect the spread insurers earn on their assets.</li>
</ol>
<p><strong>Economic scenario generators.</strong> Life liabilities contain financial options and guarantees, profit-sharing rules, management actions and policyholder behaviour, so their best estimate (BEL) is computed by Monte Carlo projection of the balance sheet in an asset–liability model, over thousands of <strong>risk-neutral scenarios</strong> that start from the Solvency II curve. Typical rate models are the displaced LIBOR market model with stochastic volatility, the two-factor Hull–White model and the displaced Black–Karasinski model, calibrated to OIS (level) and swaptions (implied volatility). The IBOR→RFR transition did not change these models: OIS and OIS swaptions replace IRS and IRS swaptions, with small adjustments to conventions.</p>
<p><strong>Measuring interest rate risk.</strong> Since cash flows of both sides depend on rates, the relevant sensitivity is the <strong>effective duration</strong>, computed by revaluation under parallel shifts <span class="math inline">\(\pm\Delta R\)</span> of the curve: <span class="math display">\[D^{ef}_A = -\frac{1}{A}\frac{\partial A}{\partial R} \approx -\frac{A^+ - A^-}{2A\,\Delta R}, \qquad D^{ef}_L = -\frac{1}{L}\frac{\partial L}{\partial R} \approx -\frac{L^+ - L^-}{2L\,\Delta R}.\]</span> <strong>Duration matching</strong> chooses the asset portfolio so that the value-weighted durations coincide, minimising the <strong>duration gap</strong> <span class="math display">\[D_{Gap} = D^{ef}_A - \frac LA\,D^{ef}_L,\]</span> so that a parallel move of rates leaves the net asset value <span class="math inline">\(A - L\)</span> approximately unchanged. Interest rate swaps and swaptions are the main hedging instruments.</p>
</section>
<section id="exercises" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="exercises"><span class="header-section-number">9.7</span> Exercises</h2>
<div class="exercise">
<p>A deposit of 100 over 182 days pays 1.60 under ACT/360 simple interest. Find the simple rate and the equivalent continuously compounded rate under ACT/365.</p>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>Solution</em>. </span><span class="math inline">\(\tau_{360} = 182/360 = 0.5056\)</span>, so <span class="math inline">\(R_s = 1.60/(100 \times 0.5056) = 3.165\%\)</span>. <span class="math inline">\(P = 1/1.016\)</span>; with <span class="math inline">\(\tau_{365} = 182/365 = 0.4986\)</span>, <span class="math inline">\(R_c = \log(1.016)/0.4986 = 3.184\%\)</span>.</p>
</div>
<div class="exercise">
<p>Verify the bootstrap formula from the par condition and recompute <span class="math inline">\(P(0, 2)\)</span> in the example.</p>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>Solution</em>. </span>At par, the floating leg <span class="math inline">\(1 - P(0, T_i)\)</span> equals the fixed leg <span class="math inline">\(S_i\sum_{j\leq i}\tau_jP(0, T_j)\)</span>; isolating <span class="math inline">\(P(0, T_i)\)</span> gives the formula. For <span class="math inline">\(T_2\)</span>: <span class="math inline">\(P(0, 2) = (1 - 0.032 \times 0.97087)/1.032 = 0.96893/1.032 = 0.93889\)</span>.</p>
</div>
<div class="exercise">
<p>Compute the ratio <span class="math inline">\(\Sigma_R/\Sigma_L\)</span> for a caplet on a 3-month period starting in 1 year, at <span class="math inline">\(t = 0\)</span>, and at <span class="math inline">\(t = T_{i-1} + 1.5\)</span> months.</p>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>Solution</em>. </span>At <span class="math inline">\(t = 0\)</span>: <span class="math inline">\(\Sigma_R^2/\sigma^2 = 1 + 0.25/3 = 1.0833\)</span> against <span class="math inline">\(\Sigma_L^2/\sigma^2 = 1\)</span>, ratio <span class="math inline">\(1.041\)</span>. Midway through the accrual period the forward-looking rate is already fixed (<span class="math inline">\(\Sigma_L = 0\)</span>), while <span class="math inline">\(\Sigma_R^2/\sigma^2 = (0.125)^3/(3\times0.25^2) = 0.0104\)</span>: the backward-looking caplet still has optionality.</p>
</div>
<div class="exercise">
<p><strong>(Duration matching; Hull 4.11–4.12)</strong> An insurer must pay <span class="math inline">\(100\)</span> in 10 years. The curve is flat at <span class="math inline">\(3\%\)</span> (continuous). It can invest in 2-year and 30-year zero-coupon bonds. Find the holdings that match present value and duration, and explain why the hedge is not perfect.</p>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>Solution</em>. </span>The liability is worth <span class="math inline">\(L = 100e^{-0.3} = 74.08\)</span> with duration <span class="math inline">\(10\)</span>. Holding present values <span class="math inline">\(x\)</span> in the 2-year and <span class="math inline">\(y\)</span> in the 30-year bond: <span class="math inline">\(x + y = 74.08\)</span> and <span class="math inline">\(2x + 30y = 10 \times 74.08\)</span>, so <span class="math inline">\(y = 21.17\)</span>, <span class="math inline">\(x = 52.92\)</span>. The portfolio is immunised against small <strong>parallel</strong> shifts, and since its convexity (<span class="math inline">\(\frac{4x + 900y}{L} = 260\)</span>) exceeds the liability’s (<span class="math inline">\(100\)</span>), it gains from larger parallel moves. It remains exposed to <strong>non-parallel</strong> moves (a steepening of the curve between 10 and 30 years), and must be rebalanced as time passes and rates change, since durations drift.</p>
</div>
<div class="exercise">
<p><strong>(Hull 4.9)</strong> A deposit pays <span class="math inline">\(4\%\)</span> per annum with continuous compounding, but interest is actually paid quarterly. How much interest is paid each quarter on <span class="math inline">\(10\,000\)</span>?</p>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>Solution</em>. </span>The equivalent quarterly-compounded rate is <span class="math inline">\(4(e^{0.01} - 1) = 4.0201\%\)</span>, so each quarter pays <span class="math inline">\(10\,000 \times 0.040201/4 = 100.50\)</span>.</p>
</div>
</section>
<section id="sources" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="sources"><span class="header-section-number">9.8</span> Sources</h2>
<p>V. Russo (Assicurazioni Generali), <em>Risk-free rates and practical implications</em>, guest lecture for the Master in Computational Finance, University of Padova, 9 December 2025 (<code>RFR_Practical</code>). References cited in the lecture: A. Lyashenko and F. Mercurio, <em>Looking forward to backward-looking rates</em>, SSRN 3330240 (2019); V. Russo and F. Fabozzi, J. Fixed Income <strong>32</strong>, 45 (2023) and <strong>35</strong>, 6 (2025), J. Derivatives <strong>31</strong>, 96 (2023); F. Fabozzi, M. Molyboga and V. Russo, J. Derivatives <strong>32</strong>, 64 (2024). The numerical examples were computed for these notes.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/08-interest-rate-modeling.html" class="pagination-link" aria-label="Interest rate modelling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interest rate modelling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/10-fx-options-market-making.html" class="pagination-link" aria-label="FX options and automated market making">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">FX options and automated market making</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Risk-free rates in practice"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Chapter 8 treated the risk-free curve as a given mathematical object. In practice it has to be **built** from market quotes, under precise conventions, and since 2023 from a new family of benchmarks. This chapter, based on a practitioner lecture by Vincenzo Russo (Assicurazioni Generali), covers market conventions, the transition from interbank offered rates (IBORs) to overnight risk-free rates (RFRs), the pricing of overnight indexed swaps, swaptions and caplets on **backward-looking** rates, the bootstrap of an RFR curve, and the use of risk-free curves in the insurance sector under Solvency II.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## The fixed-income market</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>The fixed-income market trades debt securities that pay predetermined cash flows: government bonds, corporate and covered bonds, municipal bonds, securitised products (MBS, ABS), money-market instruments. Issuers are sovereigns and financial or non-financial corporates; investors (asset managers, insurers, banks, pension funds) seek income, capital preservation, diversification and **liability matching**. Bonds differ by maturity (money market below 1 year, short 1–3, intermediate 3–7, long beyond 7), currency, structure (fixed, floating, inflation-linked, callable or putable, securitised) and credit rating (AAA down to D).</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>Prices and yields move inversely. The total yield of a risky bond decomposes as</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>$$\text{yield} = \text{risk-free rate} + \text{credit spread} + \text{liquidity premium},$$</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>so the risk-free curve is the reference for everything: **discounting** cash flows (time value of money without credit risk), **forwarding** floating rates (forward rates implied by no arbitrage), risk measures (duration, DV01, convexity), the risk-neutral drift in option pricing, and, for insurers, the fair value of both assets and liabilities.</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>**Risk-free proxies.** No asset is truly risk-free. Proxies are short-term rates anchored by central banks — government bills of top-rated sovereigns, and the new overnight benchmarks €STR (euro), SOFR (US), SONIA (UK), SARON (Switzerland), TONA (Japan) — and the derivatives written on them: futures, overnight indexed swaps (OIS). Risk-free rates are nominal: real rate plus expected inflation.</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## Market conventions</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>**Day counts.** The **year fraction** $\tau(t, T)$ between two dates depends on the day-count convention: ACT/360 (actual days divided by 360, standard for money markets), ACT/365, ACT/ACT, 30/360. For ACT/360, $\tau(T_{i-1}, T_i) = (T_i - T_{i-1})/360$ with dates counted in days.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>**Business-day rules** adjust payment dates falling on holidays: *Following* (next business day), *Modified Following* (next business day unless it crosses into the next month, then the previous one), *Unadjusted*.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>**Compounding.** A ZCB price $P(t, T)$ defines a spot rate in each convention:</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> compounding <span class="pp">|</span> definition <span class="pp">|</span> rate from price <span class="pp">|</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|</span>:--<span class="pp">|</span>:--<span class="pp">|</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> simple <span class="pp">|</span> $P = \dfrac{1}{1 + \tau R_s}$ <span class="pp">|</span> $R_s = \dfrac{1}{\tau}\Bigl(\dfrac1P - 1\Bigr)$ <span class="pp">|</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> annual <span class="pp">|</span> $P = (1 + R_a)^{-\tau}$ <span class="pp">|</span> $R_a = P^{-1/\tau} - 1$ <span class="pp">|</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $k$ times a year <span class="pp">|</span> $P = \Bigl(1 + \dfrac{R_k}{k}\Bigr)^{-k\tau}$ <span class="pp">|</span> $R_k = k\bigl(P^{-1/(k\tau)} - 1\bigr)$ <span class="pp">|</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> continuous <span class="pp">|</span> $P = e^{-R_c\tau}$ <span class="pp">|</span> $R_c = -\dfrac{\log P}{\tau}$ <span class="pp">|</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>with $\tau = \tau(t, T)$. The **zero curve** $T \mapsto R_g(t, T)$ depends on the convention $g$; the **discount curve** $T \mapsto P(t, T)$ does not, and is decreasing from $P(t, t) = 1$ when rates are positive.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>**Interpolation.** Quotes exist only for some maturities, and are sparse or illiquid at the long end. Missing points are interpolated — linearly, by cubic splines, or with parametric families such as Nelson–Siegel. For par rates $S_{T_{i-1}}, S_{T_i}$ quoted at consecutive maturities, linear interpolation gives, for $T_{i-1} &lt; T_h &lt; T_i$,</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>$$S_{T_h} = \frac{S_{T_{i-1}}(T_i - T_h) + S_{T_i}(T_h - T_{i-1})}{T_i - T_{i-1}} .$$</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>**Bonds.** A fixed-rate bond with coupon rate $K$ and dates $T_1, \dots, T_n$ is worth</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>$$B_{fx}(t, T_n) = \sum_{i=1}^nP(t, T_i)\,\tau(T_{i-1}, T_i)\,K + P(t, T_n).$$</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>For a **defaultable** issuer, market practice discounts with the risk-free zero rate plus a **zero spread** $S$: with annual compounding $\bar P(t, T) = (1 + R_a(t, T) + S)^{-\tau(t,T)}$, and the bond price uses $\bar P$ in place of $P$.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="fu">## From IBORs to RFRs</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>IBORs (Libor, Euribor) were for decades the benchmark for loans, notes and derivatives, and together with overnight rates (Fed Funds, EONIA) were treated as risk-free. During the 2007–2009 crisis the IBOR–overnight spread widened dramatically (Chapter 1), showing that IBORs contain bank credit and liquidity risk; IBOR quotes were also manipulated. Hence:</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>2013–2014: the Financial Stability Board reviews the major benchmarks and recommends alternatives;</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>2017: the UK FCA announces it will stop supporting Libor panels;</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>2019: ISDA establishes fallbacks to transaction-based overnight RFRs;</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Libor is discontinued (USD Libor on 30 June 2023), replaced by SOFR, SONIA, SARON, TONA; in the euro area €STR replaced EONIA, while **Euribor survives** in reformed, transaction-based form.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>The two kinds of rates differ structurally:</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**IBORs are forward-looking term rates**: quoted for tenors from one week to one year as simple rates, fixed at the *start* of the accrual period — a market expectation.</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**RFRs are backward-looking overnight rates**: published daily, with no term structure of their own; the rate for a period is obtained by **compounding the daily fixings in arrears**, so it is known only at the *end* of the period.</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>Correspondingly, three pricing environments have succeeded one another in a single currency:</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Single curve, IBOR** (before 2007): IBOR rates for both discounting and forwarding.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Dual curve** (after 2007): overnight rates (EONIA, Fed Funds, now €STR, SOFR) for discounting, IBOR for forwarding — still the standard for Euribor derivatives.</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Single curve, RFR, backward-looking**: the RFR curve for both discounting and forwarding. This is the setting of the rest of the chapter.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="fu">## Backward-looking rates</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>Let $C(t) = \exp\bigl(\int_0^tr(u)\,du\bigr)$ be the cash account driven by the instantaneous risk-free rate (Chapter 8), so that $P(t, T) = \mathbb E^Q\bigl<span class="co">[</span><span class="ot">e^{-\int_t^Tr(u)\,du}\bigm|\mathcal F_t\bigr</span><span class="co">]</span>$.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>::: {.definition name="Compounded-in-arrears RFR"}</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>For an accrual period $[T_{i-1}, T_i)$ with $d_i$ business days, daily fixings $r(i, j)$ and day-count fractions $\delta(i, j)$,</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>$$R(T_{i-1}, T_i) = \frac{1}{\tau(T_{i-1}, T_i)}\Bigl<span class="co">[</span><span class="ot">\prod_{j=1}^{d_i}\bigl(1 + r(i, j)\delta(i, j)\bigr) - 1\Bigr</span><span class="co">]</span> \;\approx\; \frac{1}{\tau(T_{i-1}, T_i)}\Bigl<span class="co">[</span><span class="ot">\frac{C(T_i)}{C(T_{i-1})} - 1\Bigr</span><span class="co">]</span>,$$</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>the continuous-time version being the limit of vanishing daily steps.</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>::: {.proposition name="Forward value of a backward-looking rate"}</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>For $t \leq T_{i-1}$, the expectation of $R(T_{i-1}, T_i)$ under the $T_i$-forward measure (whose numeraire is $P(\cdot, T_i)$) is</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>$$R(t, T_{i-1}, T_i) = \frac{1}{\tau(T_{i-1}, T_i)}\Bigl(\frac{P(t, T_{i-1})}{P(t, T_i)} - 1\Bigr),$$</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>the same formula as the simple forward rate of the IBOR world. For $T_{i-1} &lt; t &lt; T_i$ part of the rate is already known:</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>$$R(t, T_{i-1}, T_i) = \frac{1}{\tau(T_{i-1}, T_i)}\Bigl(\frac{e^{\int_{T_{i-1}}^tr(u)\,du}}{P(t, T_i)} - 1\Bigr).$$</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>*Proof.* Under the $T_i$-forward measure, $\mathbb E^{T_i}<span class="co">[</span><span class="ot">X\mid\mathcal F_t</span><span class="co">]</span> = \mathbb E^Q\bigl<span class="co">[</span><span class="ot">e^{-\int_t^{T_i}r}X\bigm|\mathcal F_t\bigr</span><span class="co">]</span>/P(t, T_i)$. With $X = C(T_i)/C(T_{i-1})$, $e^{-\int_t^{T_i}r}X = e^{-\int_t^{T_{i-1}}r}$, whose $Q$-expectation is $P(t, T_{i-1})$. $\square$</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="fu">### Overnight indexed swaps</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>An **OIS** exchanges a fixed rate $K$ against the compounded RFR. A payer OIS with floating dates $T_1, \dots, T_n$, fixed dates $T'_1, \dots, T'_m$ (same start and end), notional $N$, valued at $t &lt; T_0$:</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>$$OIS_R(t, T_0, T_n) = N\sum_{i=1}^nP(t, T_i)\tau(T_{i-1}, T_i)R(t, T_{i-1}, T_i) - N\sum_{j=1}^mP(t, T'_j)\tau(T'_{j-1}, T'_j)K .$$</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>By the proposition, before the start this coincides with the single-curve Libor swap formula (and the floating leg telescopes to $N(P(t, T_0) - P(t, T_n))$). Once an accrual period has started, the known part of the compounded rate must be included: the first floating coupon becomes $N\bigl(e^{\int_{T_0}^tr(u)\,du} - P(t, T_1)\bigr)$.</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="fu">### Swaptions</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>Assume the forward swap rate $S_R(t, T_0, T_n)$ is a log-normal martingale under the **swap (annuity) measure**, with numeraire the annuity $A(t) = \sum_jP(t, T'_j)\tau(T'_{j-1}, T'_j)$:</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>$$\frac{dS_R(t, T_0, T_n)}{S_R(t, T_0, T_n)} = \sigma_S\,dW_t .$$</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>Then the payer swaption follows **Black's (1976) formula**</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>$$PSWT_R(t) = N\,A(t)\bigl<span class="co">[</span><span class="ot">S_R\Phi(d_1) - K\Phi(d_2)\bigr</span><span class="co">]</span>, \qquad d_{1,2} = \frac{\log(S_R/K) \pm \tfrac12\sigma_S^2(T_0 - t)}{\sigma_S\sqrt{T_0 - t}} .$$</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>Swaption valuation is **unaffected** by whether the underlying floating rate is forward- or backward-looking: what matters is the swap rate at $T_0$.</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="fu">### Caplets on backward-looking rates</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>A caplet on $<span class="co">[</span><span class="ot">T_{i-1}, T_i</span><span class="co">]</span>$ with strike $K$ pays $N\tau(T_{i-1}, T_i)\bigl(R(T_{i-1}, T_i) - K\bigr)^+$ at $T_i$. The underlying rate keeps accruing during the period, so its uncertainty is resolved only at $T_i$. Lyashenko and Mercurio (2019) model the forward rate as a log-normal martingale under the (extended) $T_i$-forward measure, with a volatility that decays linearly during the accrual period:</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>$$\frac{dR(t, T_{i-1}, T_i)}{R(t, T_{i-1}, T_i)} = \sigma_R\min\Bigl(\frac{(T_i - t)^+}{T_i - T_{i-1}}, 1\Bigr)dW_t .$$</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>(The *extended* ZCB price — the bond maturing at $T_i$, with proceeds rolled over at the RFR after $T_i$ — keeps the numeraire defined for $t &gt; T_i$.) This gives a Black formula</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>$$CPLT_R(t) = N\tau(T_{i-1}, T_i)P(t, T_i)\bigl<span class="co">[</span><span class="ot">R(t, T_{i-1}, T_i)\Phi(d_1) - K\Phi(d_2)\bigr</span><span class="co">]</span>, \qquad d_{1,2} = \frac{\log(R/K) \pm \tfrac12\Sigma_R^2}{\Sigma_R},$$</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>with total variance</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>$$\Sigma_R^2 = \sigma_R^2\int_t^{T_i}\min\Bigl(\frac{(T_i - s)^+}{T_i - T_{i-1}}, 1\Bigr)^2ds = \sigma_R^2\Bigl<span class="co">[</span><span class="ot">\max(T_{i-1} - t, 0) + \frac{(T_i - \max(T_{i-1}, t))^3}{3(T_i - T_{i-1})^2}\Bigr</span><span class="co">]</span>.$$</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>Since a forward-looking caplet's rate is fixed at $T_{i-1}$ (variance $\sigma^2(T_{i-1} - t)$), **$\Sigma_R \geq \Sigma_L$**: the backward-looking caplet carries the extra variance of the accrual period, a third of its length.</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>::: {.example name="Forward- vs backward-looking caplet"}</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>On the curve bootstrapped below, the at-the-money caplet on $<span class="co">[</span><span class="ot">1, 2</span><span class="co">]</span>$ (forward rate $3.407\%$) with $\sigma = 20\%$ is worth $25.5$ bp of notional if the rate is forward-looking ($\Sigma_L = 0.2\sqrt1$) and $29.4$ bp if backward-looking ($\Sigma_R = 0.2\sqrt{1 + 1/3} = 0.231$).</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>The same structure holds in the one- and two-factor Hull–White models, where the caplet becomes an option on $C(T_i)/C(T_{i-1})$ and $\Sigma_R^2$ splits into the variance of the bond's forward price up to $T_{i-1}$ plus the extra variance accumulated over $<span class="co">[</span><span class="ot">T_{i-1}, T_i</span><span class="co">]</span>$.</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bootstrapping an RFR curve</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>RFR curves are stripped from OIS quoted **at par** (zero initial value), typically with annual payments on both legs. With spot start $T_0 = 0$ and par rates $S_i = S_R(0, 0, T_i)$, setting the OIS value to zero for each maturity in turn,</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>$$P(0, T_1) = \frac{1}{1 + \tau_1S_1}, \qquad P(0, T_i) = \frac{1 - S_i\sum_{j=1}^{i-1}\tau_jP(0, T_j)}{1 + \tau_iS_i}, \quad i = 2, \dots, n,$$</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>with $\tau_j = \tau(T_{j-1}, T_j)$. (This follows from the par condition $1 - P(0, T_i) = S_i\sum_{j\leq i}\tau_jP(0, T_j)$, the telescoped floating leg equal to the fixed leg.)</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>::: {.example name="A five-year OIS bootstrap"}</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>Par rates (annual payments, $\tau = 1$): 1y $3.00\%$, 2y $3.20\%$, 3y $3.35\%$, 5y $3.50\%$; the 4y rate is linearly interpolated, $3.425\%$.</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $T$ <span class="pp">|</span> par rate <span class="pp">|</span> $P(0, T)$ <span class="pp">|</span> zero rate (annual) <span class="pp">|</span> zero rate (cont.) <span class="pp">|</span></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 3.000% <span class="pp">|</span> 0.97087 <span class="pp">|</span> 3.000% <span class="pp">|</span> 2.956% <span class="pp">|</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 3.200% <span class="pp">|</span> 0.93889 <span class="pp">|</span> 3.203% <span class="pp">|</span> 3.153% <span class="pp">|</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> 3.350% <span class="pp">|</span> 0.90568 <span class="pp">|</span> 3.357% <span class="pp">|</span> 3.302% <span class="pp">|</span></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> 3.425% <span class="pp">|</span> 0.87365 <span class="pp">|</span> 3.435% <span class="pp">|</span> 3.377% <span class="pp">|</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> 3.500% <span class="pp">|</span> 0.84143 <span class="pp">|</span> 3.513% <span class="pp">|</span> 3.453% <span class="pp">|</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>With an upward-sloping curve, zero rates lie slightly above par rates, and forward rates above both (the 1-year forward from 4 to 5 years is $3.83\%$).</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>In practice (e.g. SOFR on 30 September 2024) the procedure is the same with more instruments, real day counts, a few days' spot lag and an interpolation scheme between pillars.</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="fu">## Risk-free rates in insurance: Solvency II</span></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>Under **Solvency II**, EU insurers compute their solvency ratio from a market-value balance sheet, valuing liabilities (technical provisions) and the Solvency Capital Requirement with a **regulatory risk-free curve** published by EIOPA:</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>collect par rates of IRS (Euribor) or OIS (SARON, SONIA, SOFR, …) for the liquid maturities (up to about 20 years for the euro);</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>subtract a **credit risk adjustment** (10 bp for Euribor-based curves, zero for RFR-based ones);</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**bootstrap** zero rates from the adjusted par rates;</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**extrapolate** beyond the last liquid point up to 150 years with the **Smith–Wilson** method, converging to an ultimate forward rate;</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>optionally add a **volatility adjustment** or **matching adjustment**, which reflect the spread insurers earn on their assets.</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>**Economic scenario generators.** Life liabilities contain financial options and guarantees, profit-sharing rules, management actions and policyholder behaviour, so their best estimate (BEL) is computed by Monte Carlo projection of the balance sheet in an asset–liability model, over thousands of **risk-neutral scenarios** that start from the Solvency II curve. Typical rate models are the displaced LIBOR market model with stochastic volatility, the two-factor Hull–White model and the displaced Black–Karasinski model, calibrated to OIS (level) and swaptions (implied volatility). The IBOR→RFR transition did not change these models: OIS and OIS swaptions replace IRS and IRS swaptions, with small adjustments to conventions.</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>**Measuring interest rate risk.** Since cash flows of both sides depend on rates, the relevant sensitivity is the **effective duration**, computed by revaluation under parallel shifts $\pm\Delta R$ of the curve:</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>$$D^{ef}_A = -\frac{1}{A}\frac{\partial A}{\partial R} \approx -\frac{A^+ - A^-}{2A\,\Delta R}, \qquad D^{ef}_L = -\frac{1}{L}\frac{\partial L}{\partial R} \approx -\frac{L^+ - L^-}{2L\,\Delta R}.$$</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>**Duration matching** chooses the asset portfolio so that the value-weighted durations coincide, minimising the **duration gap**</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>$$D_{Gap} = D^{ef}_A - \frac LA\,D^{ef}_L,$$</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>so that a parallel move of rates leaves the net asset value $A - L$ approximately unchanged. Interest rate swaps and swaptions are the main hedging instruments.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercises</span></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>::: {.exercise}</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>A deposit of 100 over 182 days pays 1.60 under ACT/360 simple interest. Find the simple rate and the equivalent continuously compounded rate under ACT/365.</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>::: {.solution}</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>$\tau_{360} = 182/360 = 0.5056$, so $R_s = 1.60/(100 \times 0.5056) = 3.165\%$. $P = 1/1.016$; with $\tau_{365} = 182/365 = 0.4986$, $R_c = \log(1.016)/0.4986 = 3.184\%$.</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>::: {.exercise}</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>Verify the bootstrap formula from the par condition and recompute $P(0, 2)$ in the example.</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>::: {.solution}</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>At par, the floating leg $1 - P(0, T_i)$ equals the fixed leg $S_i\sum_{j\leq i}\tau_jP(0, T_j)$; isolating $P(0, T_i)$ gives the formula. For $T_2$: $P(0, 2) = (1 - 0.032 \times 0.97087)/1.032 = 0.96893/1.032 = 0.93889$.</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>::: {.exercise}</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>Compute the ratio $\Sigma_R/\Sigma_L$ for a caplet on a 3-month period starting in 1 year, at $t = 0$, and at $t = T_{i-1} + 1.5$ months.</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>::: {.solution}</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>At $t = 0$: $\Sigma_R^2/\sigma^2 = 1 + 0.25/3 = 1.0833$ against $\Sigma_L^2/\sigma^2 = 1$, ratio $1.041$. Midway through the accrual period the forward-looking rate is already fixed ($\Sigma_L = 0$), while $\Sigma_R^2/\sigma^2 = (0.125)^3/(3\times0.25^2) = 0.0104$: the backward-looking caplet still has optionality.</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>::: {.exercise}</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>**(Duration matching; Hull 4.11–4.12)** An insurer must pay $100$ in 10 years. The curve is flat at $3\%$ (continuous). It can invest in 2-year and 30-year zero-coupon bonds. Find the holdings that match present value and duration, and explain why the hedge is not perfect.</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>::: {.solution}</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>The liability is worth $L = 100e^{-0.3} = 74.08$ with duration $10$. Holding present values $x$ in the 2-year and $y$ in the 30-year bond: $x + y = 74.08$ and $2x + 30y = 10 \times 74.08$, so $y = 21.17$, $x = 52.92$. The portfolio is immunised against small **parallel** shifts, and since its convexity ($\frac{4x + 900y}{L} = 260$) exceeds the liability's ($100$), it gains from larger parallel moves. It remains exposed to **non-parallel** moves (a steepening of the curve between 10 and 30 years), and must be rebalanced as time passes and rates change, since durations drift.</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>::: {.exercise}</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>**(Hull 4.9)** A deposit pays $4\%$ per annum with continuous compounding, but interest is actually paid quarterly. How much interest is paid each quarter on $10\,000$?</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>::: {.solution}</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>The equivalent quarterly-compounded rate is $4(e^{0.01} - 1) = 4.0201\%$, so each quarter pays $10\,000 \times 0.040201/4 = 100.50$.</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="fu">## Sources</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>V. Russo (Assicurazioni Generali), *Risk-free rates and practical implications*, guest lecture for the Master in Computational Finance, University of Padova, 9 December 2025 (`RFR_Practical`). References cited in the lecture: A. Lyashenko and F. Mercurio, *Looking forward to backward-looking rates*, SSRN 3330240 (2019); V. Russo and F. Fabozzi, J. Fixed Income **32**, 45 (2023) and **35**, 6 (2025), J. Derivatives **31**, 96 (2023); F. Fabozzi, M. Molyboga and V. Russo, J. Derivatives **32**, 64 (2024). The numerical examples were computed for these notes.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<style>
  body, p, li, h1, h2, h3, h4, h5, h6, .quarto-title-block,
  .sidebar, .toc-active, .nav-link, table, th, td, blockquote,
  figcaption, .callout, .callout-body, .quarto-figure {
    user-select: none; -webkit-user-select: none;
    -moz-user-select: none; -ms-user-select: none;
  }
  img, svg, .figure-img, .quarto-figure img {
    pointer-events: none; user-select: none;
    -webkit-user-drag: none; -webkit-touch-callout: none;
  }
  pre, pre code, code, .sourceCode, .sourceCode * {
    user-select: text !important;
    -webkit-user-select: text !important;
    -moz-user-select: text !important;
  }
</style>
<script>
  document.addEventListener('contextmenu', function(e) {
    if (!e.target.closest('pre, code, .sourceCode')) e.preventDefault();
  });
  document.addEventListener('dragstart', function(e) {
    if (e.target.tagName === 'IMG' || e.target.tagName === 'SVG') e.preventDefault();
  });
  document.addEventListener('copy', function(e) {
    var sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    var node = sel.getRangeAt(0).commonAncestorContainer;
    var el = node.nodeType === 1 ? node : node.parentElement;
    if (el && el.closest('pre, code, .sourceCode')) return;
    e.preventDefault();
  });
  document.addEventListener('keydown', function(e) {
    var k = e.key.toLowerCase();
    if ((e.ctrlKey || e.metaKey) && (k === 's' || k === 'u' || k === 'p')) {
      if (!e.target.closest('pre, code, .sourceCode')) e.preventDefault();
    }
  });
</script>
<style>
  details.solution-collapsible {
    border-left: 3px solid #b8123e;
    padding: 0.4em 0.75em;
    margin: 1em 0;
    background: #fbf3f5;
    border-radius: 0 4px 4px 0;
  }
  details.solution-collapsible > summary {
    cursor: pointer; font-weight: 600; color: #b8123e;
    list-style: none; user-select: none;
  }
  details.solution-collapsible > summary::-webkit-details-marker {
    display: none;
  }
  details.solution-collapsible > summary::before {
    content: '\25B6';
    display: inline-block; margin-right: 0.5em;
    transition: transform 0.15s ease;
  }
  details.solution-collapsible[open] > summary::before {
    transform: rotate(90deg);
  }
  details.solution-collapsible > div.solution {
    margin-top: 0.5em; border-left: none; padding-left: 0;
  }
</style>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('div.solution').forEach(function(el) {
      if (el.closest('details.solution-collapsible')) return;
      var d = document.createElement('details');
      d.className = 'solution-collapsible';
      var s = document.createElement('summary');
      s.textContent = 'Solution';
      d.appendChild(s);
      el.parentNode.insertBefore(d, el);
      d.appendChild(el);
    });
  });
</script>




</body></html>